# Generated by Django 2.2.7 on 2020-01-10 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200109_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 10, 13, 50, 15, 383554), verbose_name='Опубликована'),
        ),
    ]
