# Generated by Django 2.2.7 on 2020-01-11 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200110_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 11, 20, 17, 49, 369779), verbose_name='Опубликована'),
        ),
    ]
