# Generated by Django 2.2.7 on 2020-01-15 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200112_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 15, 19, 39, 4, 46308), verbose_name='Опубликована'),
        ),
    ]
