# Generated by Django 2.2.7 on 2020-01-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200115_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 16, 21, 28, 36, 486888), verbose_name='Опубликована'),
        ),
    ]
