# Generated by Django 2.2.7 on 2020-01-20 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200116_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 0, 13, 45, 313217), verbose_name='Опубликована'),
        ),
    ]
