# Generated by Django 2.2.7 on 2020-01-21 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200121_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 21, 11, 40, 44, 918943), verbose_name='Опубликована'),
        ),
    ]
