# Generated by Django 2.2.7 on 2020-01-23 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200121_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 23, 20, 47, 35, 680007), verbose_name='Опубликована'),
        ),
    ]
